title: Doug Weltman
description: Strategy, investments, product and new businesses
show_downloads: false
google_analytics: UA-152634683-1
theme: jekyll-theme-midnight
github:
  is_project_page: false
